version: '2'
services:
    eservice-app:
        image: eservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://eservice-postgresql:5432/eservice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eservice-postgresql:
        extends:
            file: postgresql.yml
            service: eservice-postgresql
