version: '2'
services:
    eservice-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/eservice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=eservice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
